Repository JupiterOne/graph-crowdstrike, pull requests merged in 2023-09, with the labels that each got.

#157 INT-7921: ingest applications
  docs/jupiterone.md
  src/crowdstrike/CrowdStrikeApiGateway.ts
  src/crowdstrike/FalconAPIClient.ts
  src/crowdstrike/types.ts
  src/jupiterone/converters.test.ts
  src/jupiterone/converters.ts
  src/steps/applications/__recordings__/fetch-discover-applications_1030686039/recording.har
  src/steps/applications/index.test.ts
  src/steps/applications/index.ts
  src/steps/constants.ts
  src/steps/index.ts
  src/steps/vulnerabilities/index.ts
  test/config.ts
Labels: release, minor

#165 INT-9540 - add agentId property to crowdstrike_discover_application
  src/jupiterone/converters.ts
Labels: release, patch

#166 NO-JIRA: fix pagination
  src/crowdstrike/CrowdStrikeApiGateway.ts
Labels: release, patch

#167 Add vulnerabilitiesMaxDaysInPast Config Field
  src/config.ts
  src/steps/vulnerabilities/index.ts
  src/validateInvocation.test.ts
Labels: release, minor

#169 fix: remove total class to fix pagination bug
  src/crowdstrike/CrowdStrikeApiGateway.ts
Labels: bug, release, patch
